### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by herrmannpchw** [sameersbn/docker-postgresql#120]
Hi,

I get this error trying to upgrade from 9.6 to 10:

Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Could not connect to archive.ubuntu.com:80 (91.189.88.162). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (91.189.88.161). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (91.189.88.149). - connect (111: Connection refused) Could not connect to archive.ubuntu.com:80 (91.189.88.152). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.
postgresql    | ERROR! Failed to install PostgreSQL 9.6. Exiting...
postgresql    | E: Unable to locate package postgresql-9.6
postgresql    | E: Couldn't find any package by glob 'postgresql-9.6'
postgresql    | E: Couldn't find any package by regex 'postgresql-9.6'
postgresql    | E: Unable to locate package postgresql-client-9.6
postgresql    | E: Couldn't find any package by glob 'postgresql-client-9.6'
postgresql    | E: Couldn't find any package by regex 'postgresql-client-9.6'

I think that this a proxy problem, but how could i fix it?

**Comment by sameersbn** [comment]
@herrmannpchw If this is a proxy problem then you should configure apt to talk to the proxy server. Assuming your proxy server is running accessible at 192.168.1.1 port 3128, create a file named `01proxy` with the following content:

```config
Acquire::HTTP::Proxy "http://192.168.1.1:3128";
Acquire::HTTPS::Proxy "http://192.168.1.1:3128";
```
and mount it at `/etc/apt/apt.conf.d/01proxy` while running the container, i.e.

```bash
$ docker run -v /path/to/01proxy:/etc/apt/apt.conf.d/01proxy [other args] sameersbn/postgresql:VERSION
```

**Comment by herrmannpchw** [comment]
Thank you!

**Comment by bor8** [comment]
For docker-compose:

`/etc/apt/apt.conf`
```
Acquire::http::Proxy "http://corporate-proxy:8080/";
Acquire::https::Proxy "http://corporate-proxy:8080/";
```

`docker-compose.yml`
```
# ...
    postgresql:
        environment:
            - DB_USER=*
            - DB_PASS=*
            - DB_NAME=gitlabhq_production
            - DB_EXTENSION=pg_trgm
        image: sameersbn/postgresql:12-20200524
        restart: always
        volumes:
            - /etc/apt/apt.conf:/etc/apt/apt.conf
            - ./volume_postgresql:/var/lib/postgresql:Z
        networks:
            blah:
# ...
```
