### ISSUE TITLE
sudoers: Permission denied

### ISSUE THREAD

**Issue by SRJ9** [sameersbn/docker-postgresql#123]
I got this error when I run the container (any version: latest, 9:6, ...). 

**OS:** Debian 9.6
**Kernel:** 4.9.0-8-amd64

/var/lib/docker is a mount point (partition of 92GB only with that)

```
Initializing datadir...
Initializing certdir...
Initializing logdir...
Initializing rundir...
Setting resolv.conf ACLs...
Initializing database...
sudo: unable to stat /etc/sudoers: Permission denied
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
```
In other server with same OS is working OK.

**Comment by YouSysAdmin** [comment]
This is not a system problem, it is a container security context issue.

Fix:
`docker/podman --cap-add audit_write ....`

fix for kubernetes:

add pod security policy:
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: secpolicy
  namespace: YOU_NAMESPACE
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - AUDIT_WRITE
  fsGroup:
    rule: RunAsAny
  hostNetwork: false
  hostPorts:
  - max: 5432
    min: 5432
  privileged: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
```

deployment/statefulset etc:
```
...
      containers:
        - name: postgresql
          image: sameersbn/postgresql:latest
          
          securityContext:
            capabilities:
              add: ["AUDIT_WRITE"]
....
```
