### ISSUE TITLE
How to enable domain sockets and use from a linked container?

### ISSUE THREAD

**Issue by erikano** [sameersbn/docker-postgresql#30]
From within the postgresql container:

`netstat -an`
```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:5432            0.0.0.0:*               LISTEN     
tcp6       0      0 :::5432                 :::*                    LISTEN     
udp6       0      0 ::1:58104               ::1:58104               ESTABLISHED
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node   Path
unix  2      [ ACC ]     STREAM     LISTENING     1203352  /var/run/postgresql/.s.PGSQL.5432
unix  2      [ ]         STREAM     CONNECTED     1203335  
```

I would like for communication to be over domain sockets instead of tcp if possible. Can you help me?

**Comment by erikano** [comment]
I am able to connect using tcp from a linked container but don't understand how to use domain sockets between linked containers.

**Comment by sameersbn** [comment]
@erikano The `/run/postgresql` is VOLUME mounted in the container. So you can use `--volumes-from postgresql` when running the container you want to use the unix domain socket on. 

The following command makes this a little clear.

```bash
docker run -it --rm --volumes-from=postgresql sameersbn/ubuntu:trusty ls -la /var/run/postgresql/
```

**Comment by erikano** [comment]
@sameersbn thank you, it works and now I understand docker much better :)

**Comment by maxkoryukov** [comment]
For people from Google, who want to connect a consumer container to PostgreSQL-container through _Unix-socket_.

Tested for docker-container `1.21.2` and docker `18.03.1-ce`

Here is a part of my `docker-compose.yml`:

```yaml
version: '3.2'

services:
  web:
    # ... your settings
    volumes:
      - type: 'volume'
        source: dev-postgres-run
        target: /var/run/postgresql/
    # ... your settings

  db:
    image: postgres:9.6.4
    volumes:
      - type: 'volume'
        source: dev-postgres-run
        target: /var/run/postgresql/

volumes:
  dev-postgres-run:

```

## Description

I declared a global volume `dev-postgres-run` and connected it to 
1. the container, which will connect to PostgreSql
2. to the PostgreSql container itself
