### ISSUE TITLE
Docker Compose - Master & Slave Replication

### ISSUE THREAD

**Issue by mavencode01** [sameersbn/docker-postgresql#46]
I found this really useful and am wondering how to use docker compose to start a cluster replication master & slave.

Here is my docker-compose, your example seems to run master and slave separately. I would like to just run it together with compose, any ideas ?

      PostgreSQL:
        restart: always
        image: sameersbn/postgresql:9.4-11
        ports:
          - "5432:5432"
        environment:
          - DEBUG=false
          - PG_TRUST_LOCALNET=true
          - DB_USER=app01
          - DB_PASS=app01
          - DB_NAME=AppTest
          - REPLICATION_HOST=master
          - REPLICATION_PORT=5432
          - REPLICATION_MODE=slave
          - REPLICATION_USER=app02
          - REPLICATION_PASS=app02
          - REPLICATION_SSLMODE=prefer
        volumes:
          - /srv/docker/postgresql:/var/lib/postgresql

**Comment by sameersbn** [comment]
heres an example:

```yaml
pgMaster:
  restart: always
  image: sameersbn/postgresql:9.4-11
  environment:
    - DEBUG=false

    - DB_USER=dbuser
    - DB_PASS=dbpassword
    - DB_NAME=dbname

    - DB_UNACCENT=false

    - REPLICATION_MODE=master
    - REPLICATION_USER=replicator
    - REPLICATION_PASS=replpassword
    - REPLICATION_SSLMODE=
  ports:
    - "5432"
  volumes:
    - /tmp/docker/postgresql:/var/lib/postgresql

pgSlave:
  restart: always
  image: sameersbn/postgresql:9.4-11
  links:
    - pgMaster:master
  environment:
    - DEBUG=false

    - REPLICATION_MODE=slave
    - REPLICATION_HOST=master
    - REPLICATION_USER=replicator
    - REPLICATION_PASS=replpassword
  ports:
    - "5432"
```
