### ISSUE TITLE
Enable config sidekick pattern

### ISSUE THREAD

**Issue by jmatsushita** [sameersbn/docker-postgresql#69]
With rancher, there is a pattern where sidekick containers that are ran once help provide configuration to the main container (as explained for instance [here with mongo-config](http://rancher.com/building-a-mongodb-catalog-item-for-rancher/)). With docker-postgresql this could be used to run config scripts (to add users, add databases).

This would lead to docker-compose files such as:
```
postgresql:
  labels:
    io.rancher.sidekicks: postgresql-db1,postgresql-db2
  image: sameersbn/postgresql:9.4-21
  ports:
    - "5432:5432"
  environment:
    - PG_PASSWORD=passw0rd
    - DB_EXTENSION=pg_trgm
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
postgresql-db1:
  image: sameersbn/postgresql:9.4-21
  labels:
    io.rancher.container.start_once: true
  environment:
    - DB_USER=db1
    - DB_PASS=password1
    - DB_NAME=db1
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
postgresql-db2:
  image: sameersbn/postgresql:9.4-21
  labels:
    io.rancher.container.start_once: true
  environment:
    - DB_USER=db2
    - DB_PASS=password2
    - DB_NAME=db2
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
```

I imagine this could be enabled by passing an argument to the entry point, or by checking if the db is running in the volume and acting accordingly.

cc @pierreozoux
