### ISSUE TITLE
Error trying to initialize postgresql with UID/GID Mapping

### ISSUE THREAD

**Issue by fabiorauber** [sameersbn/docker-postgresql#96]
I get the following error when trying to initialize Postgresql with UID:GID mapping:

```
git-postgresql-1 | 2017-02-17T11:26:38.206689685Z Adapting uid and gid for postgres:postgres to 70:70
git-postgresql-1 | 2017-02-17T11:26:38.225581507Z Initializing datadir...
git-postgresql-1 | 2017-02-17T11:26:39.562045683Z Initializing certdir...
git-postgresql-1 | 2017-02-17T11:26:39.566118370Z Initializing logdir...
git-postgresql-1 | 2017-02-17T11:26:39.569191309Z Initializing rundir...
git-postgresql-1 | 2017-02-17T11:26:39.590957787Z Setting resolv.conf ACLs...
git-postgresql-1 | 2017-02-17T11:26:39.595547956Z Initializing database...
git-postgresql-1 | 2017-02-17T11:26:39.958523063Z FATAL:  could not read directory "pg_notify": Unknown error 523
git-postgresql-1 | 2017-02-17T11:26:39.963100040Z child process exited with exit code 1
git-postgresql-1 | 2017-02-17T11:26:39.963121409Z initdb: removing contents of data directory "/var/lib/postgresql/9.6/main"
```

I'm using rancher-nfs for the /var/lib/postgresql volume, and it is correctly applying the owner to postgresql UID:GID 70:70.

**Comment by kenych** [comment]
Hi, I got same error, what is the solution?

**Comment by timwebster9** [comment]
Same issue here...

**Comment by kenych** [comment]
hi, apparently as a workaround, creating the postres's directory structure manually and then running the container works.

**Comment by strarsis** [comment]
For Windows (Docker Desktop and WSL) using `USERMAP_UID` and `USERMAP_GID` seems to make it work:
```yml
  postgresql:
    restart: always
    image: sameersbn/postgresql:10-2
    volumes:
    - ./data/gitlab/postgres:/var/lib/postgresql/data:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    - USERMAP_UID=1000
    - USERMAP_GID=1000
````

See 'UID/GID mapping
' in https://hub.docker.com/r/sameersbn/postgresql.
